### ISSUE TITLE
Do you accept $ bounties? I really need the relays to show up separate like in st

### ISSUE THREAD

**Issue by lacedup** [joshualyon/STWinkRelay#1]
Do you accept $ bounties? I really need the relays to show up separate like in st, in hubitat

**Comment by adamkempenich** [comment]
I submitted a PR for this. Hopefulyl Josh can get it pushed out in the coming days---and that it's still helpful for you!

**Comment by joshualyon** [comment]
I went ahead and merged PR #2 with @adamkempenich's changes. @lacedup go ahead and give it a try. 😃
