### ISSUE TITLE
APK App Crashes

### ISSUE THREAD

**Issue by RobertDaleSmith** [joshualyon/STWinkRelay#6]
Hey there! Awesome work putting this together. I would love to use it. I got most the way but when I launch the apk on my Relay it just instantly crashes. Is this an issue with the latest version possibly? Is there a newer build or source available?

**Comment by joshualyon** [comment]
This project requires root privileges. If you don't have root privileges, the app will crash when trying to load.

http://wink.boshdirect.com/#rooting-instructions
